name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-build-and-test-differential

  make-sure-require-cuda-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:require-cuda-build-and-test

  build-and-test-differential:
    needs: [make-sure-label-is-present, make-sure-require-cuda-label-is-present]
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - ""
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:universe-devel
            build-depends-repos: build_depends.repos
          - container-suffix: -cuda
            runner: codebuild-autoware-us-east-1-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
            build-pre-command: taskset --cpu-list 0-5
          - container-suffix: ""
            runner: ubuntu-latest
            build-pre-command: ""
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
        shell: bash

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Run build-and-test-differential action
        if: ${{ !(matrix.container-suffix == '-cuda') || needs.make-sure-require-cuda-label-is-present.outputs.result == 'true' }}
        uses: ./.github/actions/build-and-test-differential
        with:
          rosdistro: ${{ matrix.rosdistro }}
          container: ${{ matrix.container }}
          container-suffix: ${{ matrix.container-suffix }}
          runner: ${{ matrix.runner }}
          build-depends-repos: ${{ matrix.build-depends-repos }}
          build-pre-command: ${{ matrix.build-pre-command }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  clang-tidy-differential:
    needs: build-and-test-differential
    runs-on: ubuntu-22.04
    container: ghcr.io/autowarefoundation/autoware:universe-devel-cuda
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get changed files (existing files only)
        id: get-changed-files
        run: |
          echo "changed-files=$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD | grep -E '\.(cpp|hpp)$' | while read -r file; do [ -e "$file" ] && echo -n "$file "; done)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run clang-tidy
        if: ${{ steps.get-changed-files.outputs.changed-files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          target-files: ${{ steps.get-changed-files.outputs.changed-files }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy-ci
          build-depends-repos: build_depends.repos
          cache-key-element: cuda

      - name: Show disk space after the tasks
        run: df -h
