name: build-and-test-differential

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  CC: /usr/lib/ccache/gcc
  CXX: /usr/lib/ccache/g++

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-build-and-test-differential

  make-sure-require-cuda-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:require-cuda-build-and-test

  prepare-build-and-test-differential:
    runs-on: ubuntu-latest
    needs: [make-sure-label-is-present, make-sure-require-cuda-label-is-present]
    outputs:
      cuda_build: ${{ steps.check-if-cuda-build-is-required.outputs.cuda_build }}
    steps:
      - name: Check if cuda-build is required
        id: check-if-cuda-build-is-required
        run: |
          if ${{ needs.make-sure-require-cuda-label-is-present.outputs.result == 'true' }}; then
            echo "cuda-build is required"
            echo "cuda_build=true" >> $GITHUB_OUTPUT
          else
            echo "cuda-build is not required"
            echo "cuda_build=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Fail if the tag:run-build-and-test-differential is missing
        if: ${{ needs.make-sure-label-is-present.outputs.result != 'true' }}
        run: exit 1

  build-and-test-differential:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware:universe-devel
    needs: prepare-build-and-test-differential
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
        shell: bash

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Run build-and-test-differential action
        uses: ./.github/actions/build-and-test-differential
        with:
          rosdistro: humble
          container: ghcr.io/autowarefoundation/autoware:universe-devel
          container-suffix: ""
          runner: ubuntu-latest
          build-depends-repos: build_depends.repos
          build-pre-command: ""
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build-and-test-differential-cuda:
    runs-on: codebuild-autoware-us-east-1-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    container: ghcr.io/autowarefoundation/autoware:universe-devel-cuda
    needs: prepare-build-and-test-differential
    if: ${{ needs.prepare-build-and-test-differential.outputs.cuda_build == 'true' }}
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
        shell: bash

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Run build-and-test-differential action
        uses: ./.github/actions/build-and-test-differential
        with:
          rosdistro: humble
          container: ghcr.io/autowarefoundation/autoware:universe-devel
          container-suffix: -cuda
          runner: codebuild-autoware-us-east-1-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
          build-depends-repos: build_depends.repos
          build-pre-command: taskset --cpu-list 0-5
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  clang-tidy-differential:
    needs: [build-and-test-differential, prepare-build-and-test-differential]
    if: ${{ needs.prepare-build-and-test-differential.outputs.cuda_build == 'false' }}
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware:universe-devel
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get changed files (existing files only)
        id: get-changed-files
        run: |
          echo "changed-files=$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD | grep -E '\.(cpp|hpp)$' | while read -r file; do [ -e "$file" ] && echo -n "$file "; done)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run clang-tidy
        if: ${{ steps.get-changed-files.outputs.changed-files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy-ci
          clang-tidy-ignore-path: .clang-tidy-ignore
          build-depends-repos: build_depends.repos
          cache-key-element: cuda

      - name: Show disk space after the tasks
        run: df -h

  clang-tidy-differential-cuda:
    needs: build-and-test-differential-cuda
    runs-on: codebuild-autoware-us-east-1-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-large
    container: ghcr.io/autowarefoundation/autoware:universe-devel-cuda
    steps:
      - name: Set PR fetch depth
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Checkout PR branch and all PR commits
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1

      - name: Get changed files (existing files only)
        id: get-changed-files
        run: |
          echo "changed-files=$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD | grep -E '\.(cpp|hpp)$' | while read -r file; do [ -e "$file" ] && echo -n "$file "; done)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run clang-tidy
        if: ${{ steps.get-changed-files.outputs.changed-files != '' }}
        uses: autowarefoundation/autoware-github-actions/clang-tidy@v1
        with:
          rosdistro: humble
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/main/.clang-tidy-ci
          clang-tidy-ignore-path: .clang-tidy-ignore
          build-depends-repos: build_depends.repos
          cache-key-element: cuda

      - name: Show disk space after the tasks
        run: df -h
